const assert: typeof import('node:assert/strict') = require('node:assert/strict')
const { chromium } = require('playwright') as typeof import('playwright')
const { startIsolatedPostTestProcesses, waitPostHttp, postRoot } =
  require('./post-writer-processes.ts') as typeof import('./post-writer-processes.ts')
const { checkTextWorkspace } = require('./post-text-check.ts') as typeof import('./post-text-check.ts')
async function main() {
  const processes = await startIsolatedPostTestProcesses()
  const { apiPort, uiPort } = processes
  let browser: import('playwright').Browser | undefined
  try {
    await waitPostHttp(`http://127.0.0.1:${apiPort}/api/auth/me`, processes.backend)
    await waitPostHttp(`http://127.0.0.1:${uiPort}/`, processes.frontend)
    browser = await chromium.launch()
    const page = await browser.newPage({ viewport: { width: 1366, height: 768 } })
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(`http://127.0.0.1:${uiPort}`)
    await page.getByTestId('email-input').fill('unicornveryevil@gmail.com')
    await page.locator('input[type="password"]').fill('101010')
    await page.getByTestId('login-button').click()
    await page.getByTestId('admin-linkedin-tab').click()
    await page.getByTestId('post-writer-203').click()
    const initial = await page.request.get(`http://127.0.0.1:${uiPort}/api/admin/linkedin/accounts/203/post-writer`)
    assert.deepEqual((await initial.json()).runs, [], 'E2E must use a fresh isolated backend')
    await page.getByTestId('post-scheduled').check()
    await page.getByTestId('post-day-1').check()
    await page.getByTestId('post-day-3').check()
    await page.getByTestId('post-interval-add').click()
    await page.getByTestId('post-memes').check()
    await page.getByTestId('post-save').click()
    await page.getByTestId('post-custom-topic').fill('Go error boundaries')
    await page.getByTestId('post-cv').setInputFiles({ name: 'override.pdf', mimeType: 'application/pdf',
      buffer: Buffer.from('%PDF-1.7 mock CV') })
    await page.getByText('override.pdf', { exact: false }).waitFor()
    await page.getByTestId('post-start').click()
    await page.getByTestId('post-approve').waitFor({ timeout: 30_000 })
    assert.equal(await page.getByTestId('post-approve').isDisabled(), true)
    await page.getByTestId('post-meme-reviewed').check()
    assert.equal(await page.getByTestId('post-approve').isEnabled(), true)
    const preview = (await (await page.request.get(`http://127.0.0.1:${uiPort}/api/admin/linkedin/accounts/203/post-writer`)).json()).runs[0]
    const rejected = await page.request.post(`http://127.0.0.1:${uiPort}/api/admin/linkedin/post-runs/${preview.id}/approve`,
      { data: { contentHash: preview.hash } })
    assert.equal(rejected.status(), 409, 'backend requires explicit meme review in manual approval mode')
    await page.reload()
    await page.getByTestId('admin-linkedin-tab').click()
    await page.getByTestId('post-writer-203').click()
    await page.getByTestId('post-approve').waitFor()
    assert.equal(await page.getByTestId('post-meme-reviewed').isChecked(), false)
    assert.equal(await page.getByTestId('post-approve').isDisabled(), true)
    await page.getByRole('button', { name: 'Открыть мем крупно' }).click()
    await page.getByRole('dialog', { name: 'Мем к посту', exact: true }).waitFor()
    await page.screenshot({ path: `${postRoot}/logs/post-writer-checks/mock-meme-review.png`, fullPage: true })
    await page.keyboard.press('Escape')
    await page.getByTestId('post-meme-reviewed').check()
    assert.equal(await page.getByTestId('post-day-1').isChecked(), true)
    assert.equal(await page.getByTestId('post-manual-mode').inputValue(), 'approval_required')
    assert.equal(await page.getByTestId('post-interval-start-1').inputValue(), '16:00')
    await page.getByTestId('post-approve').click()
    await page.getByTestId('post-progress').getByRole('heading', { name: 'Пост опубликован' }).waitFor({ timeout: 30_000 })
    assert.equal(await page.getByTestId('post-progress').getByRole('link').count(), 1)
    const snapshot = await page.request.get(`http://127.0.0.1:${uiPort}/api/admin/linkedin/accounts/203/post-writer`)
    const data = await snapshot.json()
    assert.equal(data.runs.filter((run: { status: string }) => run.status === 'published').length, 1)
    assert.ok(data.runs[0].postImageId)
    assert.equal(data.runs[0].memeReviewedHash, data.runs[0].hash)
    assert.equal(data.runs[0].meme.imageCalls, 1)
    assert.deepEqual(errors, [])
    await page.screenshot({ path: `${postRoot}/logs/post-writer-checks/mock-desktop.png`, fullPage: true })
    await page.setViewportSize({ width: 1920, height: 1080 })
    await page.screenshot({ path: `${postRoot}/logs/post-writer-checks/mock-wide.png`, fullPage: true })
    await checkTextWorkspace(page, `http://127.0.0.1:${uiPort}`)
    assert.deepEqual(errors, [])
    console.log('Post Writer mock E2E passed: settings, approval, SSE, reload, read-back, no duplicate.')
  } finally { await browser?.close(); processes.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
