import assert from 'node:assert/strict';
import type { Page } from 'playwright';
import type { ClientProfilePatch } from '../backend/types.ts';

// Real form, intercepted writes: both variants, required fields and cancellation.
export async function checkStudentEducation(page: Page, writes: ClientProfilePatch[]) {
  const byId = (id: string) => page.getByTestId(id);
  const checkbox = byId('no-higher-education');
  const field = (name: string, other = false) => byId(`profile-${other ? 'other-' : ''}education-${name}${other ? '' : '-0'}`);
  const initialWrites = writes.length;
  const higher = { uni: 'Test University', faculty: 'Computer Science', grade: 'Bachelor', yearOfEnd: '2020' };
  const other = { uni: 'Колледж связи', yearOfEnd: '2021', city: 'Москва' };
  const open = () => byId('open-profile-editor-button').click();
  const save = async () => {
    await byId('save-profile-button').click();
    await byId('profile-form').waitFor({ state: 'detached' });
  };
  await open(); await checkbox.uncheck();
  for (const [name, value] of Object.entries(higher)) await field(name).fill(value);
  assert.equal(await byId('profile-other-education-city').count(), 0);
  await checkbox.check(); await byId('other-education').waitFor();
  for (const name of Object.keys(other)) await field(name, true).fill('');
  await byId('save-profile-button').click(); await byId('profile-validation-summary').waitFor();
  assert.equal(writes.length, initialWrites);
  for (const name of Object.keys(other)) assert.equal(await field(name, true).getAttribute('aria-invalid'), 'true');
  await field('uni', true).fill(other.uni); await field('yearOfEnd', true).fill(other.yearOfEnd);
  await byId('save-profile-button').click();
  assert.equal(writes.length, initialWrites, 'city is mandatory only for other education');
  await field('city', true).fill(other.city);
  await checkbox.uncheck();
  for (const [name, value] of Object.entries(higher)) assert.equal(await field(name).inputValue(), value);
  await checkbox.check();
  for (const [name, value] of Object.entries(other)) assert.equal(await field(name, true).inputValue(), value);
  await page.screenshot({ path: 'tmp/student-profile-e2e/desktop-other-education.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({ path: 'tmp/student-profile-e2e/mobile-other-education.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1100 });
  await save();
  assert.deepEqual(writes.at(-1)!.educationEntries, [{ uni: other.uni, faculty: '', grade: '', yearOfEnd: other.yearOfEnd, city: other.city }]);
  assert.equal(writes.at(-1)!.noHigherEducation, true);
  await page.reload();
  await byId('validated-student-profile').getByText('Колледж связи, 2021, Москва', { exact: true }).waitFor();
  await open();
  for (const [name, value] of Object.entries(other)) assert.equal(await field(name, true).inputValue(), value);
  await checkbox.uncheck();
  for (const [name, value] of Object.entries(higher)) await field(name).fill(value);
  await save();
  assert.equal(writes.length, initialWrites + 2);
  assert.equal(writes.at(-1)!.noHigherEducation, false);
  assert.deepEqual(writes.at(-1)!.educationEntries, [higher], 'higher education saves without city');
  await page.reload(); await open();
  for (const [name, value] of Object.entries(higher)) assert.equal(await field(name).inputValue(), value);
  await checkbox.check(); await field('city', true).fill('Cancelled city');
  await byId('profile-form').getByRole('button', { name: 'Отмена', exact: true }).click();
  await page.reload(); await open();
  assert.equal(await checkbox.isChecked(), false);
  for (const [name, value] of Object.entries(higher)) assert.equal(await field(name).inputValue(), value);
  await checkbox.check(); assert.equal(await field('city', true).inputValue(), '');
  await byId('profile-form').getByRole('button', { name: 'Отмена', exact: true }).click();
  assert.equal(writes.length, initialWrites + 2, 'cancel never writes');
}
