import { COPY_MARKER, PostgresReadError } from './contracts.mts';
import type { WorkingTable } from './working-catalog.mts';
import { quoted, tableSql } from './working-catalog.mts';
import { generatedIdColumn } from './generated-ids.mts';
const literal = (value: string) => "'" + value.replaceAll("'", "''") + "'";

// Produces an operator-reviewed script only. Never executed by application startup.
export function prepareIdentitySql(tables: readonly WorkingTable[]): string {
  if (!tables.length || new Set(tables.map(t => t.id)).size !== tables.length)
    throw new PostgresReadError('invalid_identity_tables');
  const plans = [...tables].sort((a, b) => a.id.localeCompare(b.id)).map(table => {
    const column = generatedIdColumn(table), relation = tableSql(table);
    if (column.sqlName.includes('$$')) throw new PostgresReadError('invalid_column');
    return { column, relation };
  });
  const sql = ['BEGIN;', "SET LOCAL lock_timeout='5s';", "SET LOCAL standard_conforming_strings=on;",
    `DO $$ BEGIN IF current_database() NOT IN ('unicorn_noco_copy','unicorn_noco_copy_restore') OR
      shobj_description((SELECT oid FROM pg_database WHERE datname=current_database()),'pg_database')
      IS DISTINCT FROM ${literal(COPY_MARKER)} THEN RAISE EXCEPTION 'unowned_target_database'; END IF; END $$;`,
    ...plans.map(p => `LOCK TABLE ${p.relation} IN ACCESS EXCLUSIVE MODE;`)];
  for (const { column, relation } of plans) {
    const name = quoted(column.sqlName), rel = literal(relation), col = literal(column.sqlName);
    sql.push(`DO $$ DECLARE first_id bigint; BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_index i JOIN pg_attribute a ON a.attrelid=i.indrelid
        AND a.attnum=ANY(i.indkey) WHERE i.indrelid=${rel}::regclass AND i.indisprimary
        AND i.indnatts=1 AND a.attname=${col} AND a.atttypid='bigint'::regtype)
        THEN RAISE EXCEPTION 'identity_key_mismatch'; END IF;
      IF pg_get_serial_sequence(${rel},${col}) IS NOT NULL
        THEN RAISE EXCEPTION 'identity_already_configured'; END IF;
      SELECT greatest(coalesce(max(${name}),0),0)+1 INTO first_id FROM ${relation};
      IF first_id > 9007199254740991 THEN RAISE EXCEPTION 'postgres_id_out_of_range'; END IF;
      ALTER TABLE ${relation} ALTER COLUMN ${name} ADD GENERATED BY DEFAULT AS IDENTITY
        (MAXVALUE 9007199254740991 NO CYCLE);
      EXECUTE format('ALTER TABLE %s ALTER COLUMN %I RESTART WITH %s',${rel},${col},first_id);
    END $$;`);
  }
  return sql.concat('COMMIT;', '').join('\n');
}
