import test from 'node:test';
import assert from 'node:assert/strict';
import { prepareIdentitySql } from './identity-plan.mts';
import { assertGeneratedIds } from './identity-preflight.mts';
import { createWorkingCatalog } from './working-catalog.mts';
import { metadata, workingFake } from './working-fixture.mts';
const table = () => createWorkingCatalog(metadata.map(definition => ({ definition }))).get('mpeople');

test('identity plan locks before reading max, preserves keys, bounds IDs; is not executed', () => {
  const t = table(), before = structuredClone(t), sql = prepareIdentitySql([t]);
  assert.deepEqual(t, before);
  assert.ok(sql.indexOf('ACCESS EXCLUSIVE') < sql.indexOf('max('));
  for (const fragment of ['unowned_target_database', 'identity_key_mismatch', 'identity_already_configured',
    'GENERATED BY DEFAULT AS IDENTITY', 'MAXVALUE 9007199254740991 NO CYCLE', 'RESTART WITH', 'COMMIT;']) assert.ok(sql.includes(fragment));
  assert.doesNotMatch(sql, /UPDATE noco|DELETE|DROP|setval/i);
  assert.throws(() => prepareIdentitySql([t, t]));
  t.columns[0].sqlType = 'text'; assert.throws(() => prepareIdentitySql([t]), /record_key_required/);
});
test('startup preflight only reads; missing allocator cannot run DDL or allocate an ID', async () => {
  for (const ready of [false, true]) {
    const { pool, state } = workingFake(), original = pool.connect;
    pool.connect = async () => {
      const s = await original();
      return { ...s, async query(text, values) {
        const r = await s.query(text, values);
        return text.includes('has_sequence_privilege') ? { rows: [{ ready }] } : r;
      } };
    };
    if (ready) await assertGeneratedIds(pool, 'unicorn_noco_copy_restore', [table()]);
    else await assert.rejects(assertGeneratedIds(pool, 'unicorn_noco_copy_restore', [table()]), /postgres_id_allocator_required/);
    assert.equal(state.calls.at(-1)?.text, 'ROLLBACK');
    assert.ok(!state.calls.some(c => /INSERT|UPDATE|ALTER|nextval/.test(c.text)));
  }
});
