import type { AutomationStore } from './contracts.ts'
export const explanations: Record<string,string> = {
  automation_not_configured:'Автоматизация не подключена на этом backend.',
  automation_startup_failed:'Не удалось запустить LinkedIn-модуль. Его отправки отключены; остальные разделы консоли доступны.',
  automation_schema_required:'Схема оркестратора LinkedIn отсутствует или несовместима. Обновите её миграцией и перезапустите backend. Отправки LinkedIn отключены.',
  postgres_read_failed:'Не удалось прочитать SQL-хранилище LinkedIn. Проверьте схему и права доступа; отправки отключены.',
  database_not_allowed:'SQL-подключение LinkedIn не прошло проверку базы. Отправки отключены.',
  automation_comments_inactive_day:'Комментарии на паузе: на сегодня нет активности в расписании (МСК).',
  automation_comments_waiting_for_post:'Комментарии ждут подтверждённой публикации первого поста.',
  automation_comments_yielding:'Комментарии уступают аккаунт другой задаче. После её завершения монитор продолжит работу.',
  comment_policy_changed:'Случайный запуск комментариев заменён фоновым режимом в активные дни.',
  published_post_added:'Новый подтверждённый пост добавлен в монитор. Лимиты и история ответов сохранены.',
  automation_worker_stopping:'Backend завершает работу. Сначала сохраняется результат уже отправленного запроса.',
  automation_withdrawal_import_required:'Перенос журнала отзывов в SQL не завершён. Запуск заблокирован.',
  automation_withdrawal_import_conflict:'Журнал отзывов в файлах и SQL различается. Нужно сверить попытки и неопределённые результаты.',
  duration_estimate:'Оценивается время выполнения фичи с учётом оставшегося объёма и пауз.',
  stop_requested:'Остановка запрошена. Проверяется результат уже отправленного запроса; новые отправки запрещены.',
  task_time_limit:'Превышен лимит длительности задачи. Новые действия остановлены; проверяется результат уже отправленного запроса.',
  automation_task_timeout:'Истёк лимит длительности задачи. Следующая внешняя отправка запрещена.',
  waiting_for_pause:'Выдерживается сохранённая случайная пауза после предыдущей задачи этого ученика.',
  write_authorized:'Перед следующим действием сохранена запись в журнал и проверены права исполнителя.',
  result_verified:'Результат внешней операции подтверждён повторным чтением и сохранён.',
  result_not_confirmed:'Подтверждённой отправки нет. Проверьте причину пропуска или неопределённый результат в соседних событиях.',
  monitor_already_running:'Монитор уже включён; повторный запуск не нужен.',
  automation_preview_only:'Включён предварительный просмотр, автоматические отправки запрещены.',
  unipile_timeout:'Unipile не ответил вовремя. Если запрос уже отправлен, сначала проверяется его результат.',
  unipile_service_unavailable:'Unipile временно недоступен.',
  unipile_api_too_many_requests:'Достигнут лимит запросов Unipile. Следующая проверка отложена до разрешённого времени; отправленный запрос повторно не отправляется.',
  unipile_provider_too_many_requests:'LinkedIn ограничил запросы аккаунта. Новые запросы приостановлены; проверяется результат уже отправленного действия.',
  connection_invitation_result_pending:'Приглашение отправлено, но проверка результата отложена из-за недоступности метода Unipile. Повторной отправки не будет.',
  connection_writer_disabled:'Отправка приглашений отключена в настройках backend.',
  stack_required:'Не выбран стек ученика. Укажите его в приглашениях.',
  post_writer_read_only:'Публикация постов отключена в настройках backend.',
  comment_monitor_auth_required:'Для комментариев требуется проверенный LinkedIn-аккаунт.',
  comment_monitor_posts_missing:'В аккаунте нет постов для мониторинга комментариев.',
  comment_reply_uncertain:'Отправка комментария не подтверждена. Сначала требуется проверка результата.',
  withdrawal_check_required:'Нужно проверить результат предыдущего отзыва приглашения.',
  postgres_read_unavailable:'База данных недоступна. Новые отправки запрещены до восстановления связи.',
  postgres_write_failed:'Не удалось сохранить состояние в SQL. Новые отправки запрещены.',
  commit_uncertain:'Ответ SQL на сохранение потерян. Сначала требуется повторное чтение состояния.',
  waiting_for_queue:'Ожидает свободного места в очереди.', waiting_for_account:'Аккаунт занят другой операцией.',
  window_too_short:'Интервал слишком короткий с учётом обязательных пауз и запаса времени.',
  provider_limit_outside_slot:'Лимит Unipile не позволит выполнить задачу в этом слоте. Ожидается следующий разрешённый слот; другие фичи продолжают работу.',
  insufficient_time:'До конца интервала осталось недостаточно времени. Ожидается следующий слот.',
  window_closed:'Интервал закончился до начала задания.', schedule_changed:'Запланированное задание отменено после изменения расписания.',
  disabled_by_admin:'Автоматизация выключена. Новые действия остановлены.',
  automation_disabled:'Автоматизация выключена; новый запрос не отправлен.',
  automation_writer_active:'Исполнитель уже работает в другом backend.',
  automation_writer_unavailable:'Потеряно соединение с БД или право исполнения. Новые записи запрещены.',
  automation_audit_unavailable:'Не удалось сохранить журнал. Новые внешние записи запрещены.',
  manual_task_active:'У аккаунта есть ручное задание; автоматизация его не заменяет.',
  feature_run_missing:'Сохранённое задание фичи не найдено. Нужна проверка хранилища.',
  automation_feature_unavailable:'Ошибка фичи. Проверьте последний сохранённый этап и связанное задание.',
  uncertain:'Сервис мог принять запрос, но результат пока не подтверждён. Повторная отправка запрещена.',
  worker_stale:'Исполнитель давно не обновлял статус: процесс остановлен, потерял БД или завис.',
  worker_missing:'Исполнитель ещё не записал статус в эту базу.',
  starting:'Задание сохранено и передаётся исполнителю.',
  worker_restarted:'Backend запущен заново. Сохранённые задания проверяются перед продолжением.',
  running:'Задание выполняется.', monitoring:'Монитор комментариев включён.',
  deferred:'Проверка результата отложена до разрешённого времени. Исполнитель освобождён для других фич.',
  planned:'Ожидает сохранённого времени запуска.', completed:'Задание завершено.',
  blocked:'Задание остановлено до выяснения причины.', cancelled:'Задание отменено.', missed:'Запуск пропущен.'
}
export function explain(code: string) { return explanations[code] ?? `Код ошибки или состояния: ${code}. Откройте журнал запуска.` }
export async function readAutomationDiagnostics(store: AutomationStore, now: number,
  query: {account?:number;runKey?:string;before?:number;limit?:number} = {}) {
  const [worker,settings,runs,events] = await Promise.all([store.heartbeat(),store.settings(),store.runs(query.account),store.events(query)])
  const healthy = Boolean(worker && worker.state === 'ready' && now - worker.at < 30_000 && worker.at <= now + 5000)
  const code = !worker ? 'worker_missing' : !healthy ? worker.code ?? 'worker_stale' : 'ready'
  return { checkedAt:now,healthy,code,description:healthy ? 'Исполнитель отвечает.' : explain(code),worker,
    settings:settings.filter(s => query.account === undefined || s.account === query.account),
    runs:runs.filter(r => !query.runKey || r.key === query.runKey).map(r => ({...r,description:explain(r.reason ?? r.state) + (r.state==='deferred' && r.nextActionAt ? ` Следующая проверка: ${new Date(r.nextActionAt).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})} МСК.` : '')})),
    events:events.map(e => ({...e,description:explain(e.code)})),nextBefore:events.at(-1)?.id }
}
